# check-status.yml
---
  - hosts: webservers:loadbalancer
    become: true
    tasks:
      - name: Check status of apache
        #command: service httpd status
        #service: name=httpd
        shell: 
          cmd: service httpd status
          warn: False